---
name: docker-compose up

on:
  push:
  schedule:
    # Every Sunday morning
    - cron: "15 4 * * *"
jobs:
  build:
    name: init and up
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
    steps:
      - uses: actions/checkout@v3

      - name: init
        run: bin/metacpan-docker init

      - name: up api
        run: docker-compose up -d api
      - name: down
        run: docker-compose down

      - name: up api_test
        run: docker-compose up -d api_test
      - name: down
        run: docker-compose down

      - name: up github-meets-cpan
        run: docker-compose up -d github-meets-cpan
      - name: down
        run: docker-compose down

      - name: up github-meets-cpan-cron
        run: docker-compose up -d github-meets-cpan-cron
      - name: down
        run: docker-compose down

      - name: up web
        run: docker-compose up -d web
      - name: down
        run: docker-compose down

      - name: up grep
        run: docker-compose up -d grep
      - name: down
        run: docker-compose down
